eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        data: debug
server:
  port: ${PRODUCT_SERVICE_PORT:8082}
  
spring:
  datasource:
    password: ${PRODUCT_DB_PASSWORD:password}
    url: jdbc:mysql://${PRODUCT_DB_IP:192.168.99.101}:${PRODUCT_DB_PORT:31093}/${PRODUCT_DB_SCHEMA:product_db}
    username: ${PRODUCT_DB_USERNAME:root}
  application:
    name: ${APP_NAME:product-service}
    

ribbon:
  eureka:
    enabled: true
